name: Deploy
on:
  workflow_call:
    secrets:
      MY_SECRET:
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Is secret available?
        run: |
          echo "MY_SECRET: ${{ secrets.MY_SECRET }}"