name: Test
on:
  push:
    branches:
      - '*'

jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - name: Check variables
        id: checks
        run: echo "is_ios_affected=true" >> $GITHUB_OUTPUT
          
  Second:
    runs-on: ubuntu-latest
    needs: First
    steps:
      - name: Print name
        shell: bash
        run: |
          echo "Actor ${{ github.actor }}"
          echo "is_ios_affected: ${{ needs.First.steps.checks.outputs.is_ios_affected }}"