name: Test
on:
  push:
    branches:
      - '*'

jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: true

      - name: Install packages
        run: npm install

      - name: Run code
        run: node index.js
        env:
          RELEASE_TARGET: minor
  
  # First:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     is_ios_affected: ${{ steps.checks.outputs.is_ios_affected }}
  #   steps:
  #     - name: Check variables
  #       id: checks
  #       run: |
  #         echo "is_ios_affected=true" >> $GITHUB_OUTPUT

  #     - name: Is secret available?
  #       run: |
  #         echo "MY_SECRET: ${{ secrets.MY_SECRET }}"

  # Second:
  #   needs: First
  #   if: ${{ needs.First.outputs.is_ios_affected == 'true' }}
  #   uses: ./.github/workflows/deploy.yml
  #   secrets:
  #     MY_SECRET: ${{ secrets.MY_SECRET }}
          
  # second:
  #   runs-on: ubuntu-latest
  #   needs: First
  #   if: ${{ needs.First.outputs.is_ios_affected == 'true' }}
  #   steps:
  #     - name: Print name
  #       shell: bash
  #       run: |
  #         echo "Actor ${{ github.actor }}"
  #         echo "is_ios_affected: ${{ needs.First.outputs.is_ios_affected }}"