name: Test
on:
  push:
    branches:
      - '*'

jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - name: Check variables
        id: checks
        run: echo "is_ios_affected=true" >> $GITHUB_OUTPUT
          
  Second:
    needs: First
    runs-on: ubuntu-latest
    if: ${{ needs.First.steps.checks.checks }}
    steps:
      - name: Print name
        shell: bash
        run: |
          echo "Actor ${{ github.actor }}"